### ISSUE TITLE
3D Spectrograms

### ISSUE THREAD

**Issue by MohSamNaf** [irfankhaan/DL-Models-for-Seizure-Detection-using-Spectrograms#1]
Hi Irfan,
Thank you for sharing your amazing work. It is very useful.

May I know how did you generate the 3D spectrograms?
Thank you

**Comment by irfankhaan** [comment]
Hi,

Thank you for showing your interest in this project.
I had actually used the Python Matplotlib library to generate 2D and 3D
spectrograms.
3D spectrograms were not fed into the CNN networks. The 3D spectrograms are
for representation purposes only.

The following code snippet was used for generating 2D spectrograms from the
one dimensional EEG signal.
import matplotlib.pyplot as plt
f, Sxx, t, im = plt.specgram(epoch_toplot_b, Fs=Fs, NFFT=NFFT, window=np.
hamming(wlen), noverlap=noverlap, detrend=detrend,cmap='jet')

In a similar manner using the outputs from the above line, the 3D
spectrograms were generated as follows.
fig = plt.figure()
ax = fig.gca(projection='3d')

ax.plot_surface(Sxx[:, None], np.transpose(t[:, None]), 10.0*np.log10(f),
cmap="jet")
ax.set_xlabel('Frequency (in Hz)')
ax.set_ylabel('Time (in Seconds)')
ax.set_zlabel('Power (in dB)')

plt.title("gnsz")
plt.show()

I have attached the notebook where I generated the spectrograms in this
email as well but the code is unpolished and might not be easily understood.
Please let me know if you want me to share a more polished version of the
notebook with you. I will be happy to help.

Thanks and regards.
Irfan Khan

**Comment by MohSamNaf** [comment]
Hi Irfan,
Thank you for your reply. 

I have tried modifying the code, but the generated 3D map has no jet sketch
`raw = mne.io.read_raw_fif(path, preload=True, verbose=0)
raw.notch_filter(freqs=np.arange(60,128,60), verbose=0)
raw.filter(l_freq=0.5, h_freq=50, iir_params=None, method="iir", verbose = 0)
epoch = mne.make_fixed_length_epochs(raw, duration=3, preload=True, verbose = 0, overlap = 0) #3 seconds duration

epoch_toplot_b = stats.trim_mean(epoch, 0.2)

f, Sxx, t, im = plt.specgram(epoch_toplot_b, Fs=256, NFFT=256, window=np.hamming(256), noverlap=0,  detrend='none' ,cmap='jet')

fig = plt.figure()
ax = fig.gca(projection='3d')    

ax.plot_surface(Sxx[:, None], np.transpose(t[:, None]), 10.0*np.log10(f),
cmap="jet")
ax.set_xlabel('Frequency (in Hz)')
ax.set_ylabel('Time (in Seconds)')
ax.set_zlabel('Power (in dB)')

plt.title("gnsz")
plt.show()`

![image](https://user-images.githubusercontent.com/112216648/194421338-e21e1f9d-3726-42c7-9150-c90c6ebbea42.png)

May I know what is wrong with this code?
Thank you

**Comment by irfankhaan** [comment]
Hi,

I don't think there is anything wrong with your code but it could be possible that the map didn't generate because of dimension mismatch in the parameters provided to ```ax.plot_surface()```.
Please check the dimensions of ```f, Sxx, t``` once and let me know if the problem still persists.
Also, if you are getting any sort of error or warning please share it here as well. 

I hope this will help.
Thanks.
